### ISSUE TITLE
Update Heading for Speaker or Amp based on odometry 

### ISSUE THREAD

**Issue by Tan560** [Team302/2024Crescendo#240]
Please update label correctly, don't know where vision drive falls under. 

Update Maintain Heading to point towards the Speaker or Amp based on odometry until vision detects an april tag, then switch to vision for heading. (Like what we did in 2022 Rebound Rumble)

Speaker Heading:
Blue = 180
Red = 0

Amp Heading
Blue = 90
Red = -90

**Comment by witcpalek** [comment]
@Tan560 I don't think that is how we want to do it.  These are separate heading options.

**Comment by witcpalek** [comment]
closing this one and creating several more.
