### ISSUE TITLE
Mount 2 arducams on the practice robot

### ISSUE THREAD

**Issue by nickfrisch** [Team302/2024Crescendo#433]
Relies on #432
Parallel with #431
Need to mount two Arducams (doesn't matter which) on the practice bot once they have been calibrated.
These will be the Placer and Launcher cameras for detecting AprilTags.

Don't forget to rename the cameras inside of PhotonVision as Placer or Launcher (I think it is case-sensitive as well so type exactly what is written there)

**Comment by notcharlie2026** [comment]
need to make code gen accept negative values for camera offsets to finish this.
