### ISSUE TITLE
Compare new dataset colab model with donut/90fps detector model

### ISSUE THREAD

**Issue by nickfrisch** [Team302/2024Crescendo#434]
Go to [DatasetColab](https://datasetcolab.com/models) and test both the SSD-MobileNetV2 model  and EfficientDet model on one of the Limelight 3s.
Compare the performance to the donut model and also try out the robot detection as well.
(We can probably sacrifice a bit of performance from 90fps if we can detect robots and notes)
If they perform well, upload to vision/docs/mlModels named something like NotesandRobots

**Comment by ImAPenguin56** [comment]
the models do not work, and donut detector remains the best option
