### ISSUE TITLE
Look at photonlib recommendations

### ISSUE THREAD

**Issue by nickfrisch** [Team302/2024Crescendo#643]
Reject all tag poses where the ambiguity ratio (availiable via PhotonLib) is greater than 0.2.
Some settings recommendations: https://docs.photonvision.org/en/latest/docs/apriltag-pipelines/2D-tracking-tuning.html
Camera mounting position should be in robot space
Camera coordinate space is much different from robot space (axis' are different)

**Comment by notcharlie2026** [comment]
According to the photon lib docs, it looks like the default values are recommended.
