### ISSUE TITLE
Make apriltag positions dynamic

### ISSUE THREAD

**Issue by notcharlie2026** [Team302/2024Crescendo#804]
Not sure if we want to go back to xml parsing for this or store it in a normal header file, but we want to be able to easily edit the relative positions of the April tags, so that it's easier to calibrate per field.

**Comment by witcpalek** [comment]
Charlie - why are creating issues on a closed project instead of using the current offseason project?

**Comment by witcpalek** [comment]
Added into current project; deleted the existing issue.  Added labels.

Previous issue was:

Make Field April Tags Dynamic/Configurable during field calibration
